name: transparent_image
description: A transparent image in Dart code, represented as a Uint8List.
version: 1.0.0
homepage: https://github.com/brianegan/transparent_image
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=1.24.1 <3.0.0'
